### ISSUE TITLE
Xcode 협업 시 추적 파일 구성은 어떻게 하나요?

### ISSUE THREAD

**Issue by jwchoi179** [jwchoi179/TableViewWithAPI#3]
# Xcode 협업 시 추적 파일 구성은 어떻게 하나요?

- `.gitignore` 파일을 정리하다보니 staged 되어야 하는 파일 항목들을 어떻게 구성해야 하는지 궁금해졌습니다. 협업 시 순수하게 `Swift` 코드 파일만 공유를 하는지 궁금합니다. 
- 실질적으로 앱이 완성되고 `xcodeproj` 파일을 업로드 할 때만 다시 추적하게 `.gitignore`를 수정해서 업로드 하는지도 궁금해요.

**Comment by binisnil** [comment]
허허 이건 보통 쓰는 개꿀팁사이트가 있습니다! 처음 프로젝트 세팅을 할 때 .DSStore와 같은 필요 없는 파일들을 걸러내기 위한 .gitignore파일을 만들잖아요? 근데 하나씩 적어주기 너무 귀찮고, 빼먹는게 많을 수도 있으니 보통 아래 사이트를 활용해서 gitignore파일을 만들어주곤 해요

[.gitignore파일 쉽게 만드는 개꿀팁 사이트](https://www.toptal.com/developers/gitignore)

위의 사이트에 Swift, XCode 등 iOS 개발과 관련된 단어를 입력한 후에 버튼을 누르면 파일을 생성해줍니다!

그리고 또 야무지게 만들어 둔 .gitignore 파일을 그대로 가져다 쓰는 경우도 존재하죠,, ㅎㅎ <- 이건 제가 사용하는 방법인데 원하신다면 공유해드릴게요!

**Comment by jwchoi179** [comment]
오! 야무지게 만들어둔 파일이 어떤 건지 궁금해. 많은 레퍼런스들을 보는 걸 좋아해서 공유받고 싶어요~

**Comment by kimsoomin20221789** [comment]
제 경험상 gitignore 파일을 중간에 수정하진 않았고, 한번 만들어놓고 계속 유지시켰어요. 협업시에는 Swift파일과, 프로젝트 파일을 모두 업로드해서 깃헙에 올리곤 합니다!

**Comment by jwchoi179** [comment]
`gitignore`에 작성해야 하는 항목들에 대해서는 앞으로 프로젝트를 하면서 찬찬히 알아봐야겠다. 많은 도움을 주신 분들께 감사드려요.
