### ISSUE TITLE
UIKit에서 UIViewController에서 Live Preview는 실질적으로 작업 시 사용하는지 여부

### ISSUE THREAD

**Issue by jwchoi179** [jwchoi179/TableViewWithAPI#6]
# UIKit에서 UIViewController에서 Live Preview는 실질적으로 작업 시 사용하는지 여부

- #5 에서 확인할 수 있지만, UIKit에서 SwiftUI의 강력한 기능 중 `Live Preview`를 사용할 수 있다.
- 궁금한 점은, 실질적으로 작업 시 `Live Preview`를 사용하는지 궁금하다.

**Comment by binisnil** [comment]
제 주변에서 Hot Reload를 활용해서 뷰를 확인하는 경우는 잘 못본 것 같아요! 보통 그냥 빌드를 해서 확인하는게 대부분이었습니당 그래도 Hot-Reload만의 장점이 따로 있을테니, 이게 편하다면 사용하는걸 굳이 지양하라고 말하고 싶지는 않네요!

**Comment by kimsoomin20221789** [comment]
나는 UIKit을 사용하면서 LivePreview를 사용한적은 없지만, 본인이 개발하기에 편하다면 사용하는게 좋지 않을까??

**Comment by jwchoi179** [comment]
많은 생각들을 나누어주신 분들께 고마워요!
